### ISSUE TITLE
pnpm install 按照 README 提示安装页面不显示组件

### ISSUE THREAD

**Issue by xiangshu233** [zhiyuanzmj/form-design#1]
vue 警告找不到 组件
![image](https://github.com/zhiyuanzmj/form-design/assets/49575330/87c26349-1388-4f56-ac88-ba200f84c307)

**Comment by xiangshu233** [comment]
请问项目不维护了吗

**Comment by zhiyuanzmj** [comment]
是的 很长时间没维护这个库了 你可以直接引用它
```ts
<script setup>
import { DesignForm } from '@zmjs/form-design'
</script>
```
https://github.com/zhiyuanzmj/form-design/blob/master/playground/src/App.vue

**Comment by xiangshu233** [comment]
@zhiyuanzmj  感谢大佬回复，成功引用了，想请教下为什么直接引用却可以 :) 
请问后续还继续维护它吗

**Comment by zhiyuanzmj** [comment]
因为我没写use 需要的install方法
https://vuejs.org/guide/reusability/plugins.html

以后有需要的可能会维护 这个库我也是复制别的人的库魔改的 你也可以自己fork下来试试

**Comment by xiangshu233** [comment]
@zhiyuanzmj  好的，感谢大佬，我正打算微创新（cv）一下

**Comment by xiangshu233** [comment]
打扰了，请问大佬，clone 项目拉到本地后没找到dev启动环境，因为需要二开，要热更新，手动添加 dev  启动命令后启动无法显示网页是怎么回事，而且每次改动右下角直接卡死
![image](https://github.com/zhiyuanzmj/form-design/assets/49575330/05148df8-fac1-4fd0-8a18-83d2b45a770c)
![image](https://github.com/zhiyuanzmj/form-design/assets/49575330/d1519546-ec67-4717-a999-8a0ab2cfa5a8)

**Comment by zhiyuanzmj** [comment]
你可以先 pnpm dev
再运行 pnpm play 去调试

**Comment by xiangshu233** [comment]
@zhiyuanzmj  打扰了大佬，还想再请教一个问题
使用 
pnpm dev
pnpm play 修改好像没有热更新，所以我干脆直接 cv 源码到demo 里去了
但是执行到 拖拽 `add()` 事件的时候 `@add="selectWidget=list[$event.newIndex]"` 它并没有给 `selectWidget` 赋上值，还是 `undefind`
这样就会导致 `WidgetFormItem` 组件内部高亮显示失效 `active: selectWidget?.key === element.key`，想问下大佬这是什么情况，我从头到尾捋了一遍 `selectWidget` 这个变量，它的赋值阶段就是在 `Draggable` 拖拽的时候执行 `add` 事件内赋值的


https://github.com/zhiyuanzmj/form-design/assets/49575330/ec391b5b-97f3-489d-b1c7-9357a5bf367a

希望大佬指点指点 :)

**Comment by xiangshu233** [comment]
大佬代码写的太强了，逻辑很清晰，二开起来很方便 :)
